# Get database config and credentials.

<% File.open("#{Rails.application.config.database_yml_file_path}", 'r') do |file| %>
<% while line = file.gets %>
<%= line %>
<% end %>
<% end %>

test:
  adapter: postgresql
  encoding: unicode
  database: ned_test
